### ISSUE TITLE
Some gcode fails to generate proper tower

### ISSUE THREAD

**Issue by cfelicio** [spegelius/filaswitch#19]
Not sure what's going on here, but it fails to generate the top portion of the tower. I'm attaching the original gcode for reference, the stls and the processed gcode.

![image](https://user-images.githubusercontent.com/7227683/33051531-328cfcea-ce1f-11e7-93a9-e7251d60fa1a.png)

[traffic cone.zip](https://github.com/spegelius/filaswitch/files/1489804/traffic.cone.zip)

[stls.zip](https://github.com/spegelius/filaswitch/files/1489806/stls.zip)

**Comment by spegelius** [comment]
Hmm strange. I'll have a look

**Comment by spegelius** [comment]
Fix committed to master

**Comment by cfelicio** [comment]
awesome, thanks so much!! :-)
