### ISSUE TITLE
Odd tower raft behavior

### ISSUE THREAD

**Issue by paukstelis** [spegelius/filaswitch#28]
Just notice today that if I place parts below the build plate I got an odd raft dimension for the tower:
![screenshot from 2018-01-12 16-30-11](https://user-images.githubusercontent.com/28326982/34896222-efe00d76-f7b6-11e7-8912-bb399f8649a3.png)

![screenshot from 2018-01-12 16-29-56](https://user-images.githubusercontent.com/28326982/34896228-f5b5684a-f7b6-11e7-92f6-a4c5b51ea3ac.png)
However, if I sit the object on the build plate, everything is fine.
![screenshot from 2018-01-12 16-31-16](https://user-images.githubusercontent.com/28326982/34896238-088e3cc6-f7b7-11e7-8bc1-bf972f3ad6d1.png)

Obviously, this isn't a huge issue, but something that might need to be looked at in the future.

**Comment by spegelius** [comment]
Hmm strange. I'll have a look

**Comment by spegelius** [comment]
I might've found the reason for this; the new preprime messes the calculation for how many max changes are per layer and raft is too big. Fixed it on my cfgfiles branch

**Comment by paukstelis** [comment]
Closing this. I tried to reproduce this in the latest cfgfiles branch and it did not happen.
