### ISSUE TITLE
Feature request: Prusa MMU support

### ISSUE THREAD

**Issue by laird** [spegelius/filaswitch#30]
The new Multi Material Upgrade from Prusa is only supported by a post-processor for their version of Slic3r. I’d rather use S3D, and from forum posts many others feel the same way.

Is there any interest in adding support for the Prusa MMU to filaswitch?

**Comment by spegelius** [comment]
It just so happens that such support is already implemented :). Not on master branch yet, but soon, I'll release new version when the code is tested. Check out cfgfiles branch and the feature pull request: https://github.com/spegelius/filaswitch/pull/25.

**Comment by laird** [comment]
I just found https://github.com/spegelius/filaswitch/tree/cfgfiles . Very exciting! My MMU is supposed to show up in a month or two (MK3 MMU isn’t shipping yet, AFAIK), after which I’ll be happy to test, help code, etc.

**Comment by laird** [comment]
Since it’s Implemented, should I close this issue? Or wait for the merge?

**Comment by spegelius** [comment]
Well technically it's not released yet :). But either way works for me, it'll be released soon anyways

**Comment by spegelius** [comment]
Released in 0.16.1
