### ISSUE TITLE
Brim size to follow model brim size

### ISSUE THREAD

**Issue by spegelius** [spegelius/filaswitch#37]
Bigger brim would be good on some occasions. Following the settings for the print would be a good option

**Comment by wbarber69** [comment]
it could have a benefit, but the raft seems to function pretty good as it is

**Comment by spegelius** [comment]
This was a request from user on Prometheus forums, had problems with tower detaching mid print. Had that problem a couple of times, but had problems with objects sticking in general. Still, it's not a big change and I have to look into that code anyways, so might as well improve it.

**Comment by spegelius** [comment]
Released on 0.17.0 (I think)
