### ISSUE TITLE
Curl scripting.

### ISSUE THREAD

**Issue by wbarber69** [spegelius/filaswitch#45]
Could it be possible to implement the curl script im using in s3d to upload files directly into octoprint, only instead append it to the end of filaswitch.bat so that the output of filaswitch will be the file that gets uploaded?

**Comment by spegelius** [comment]
It's possible, but I'd rather do the upload in fs. I've been planning an option for OctoPrint, it should be quite straightforward to do the upload. API key and upload folder would be configurable in GUI/CLI.

**Comment by wbarber69** [comment]
This is exactly what I was hoping.

Sent from my iPhone

On Apr 16, 2018, at 12:55 AM, Pekka Piippo <notifications@github.com<mailto:notifications@github.com>> wrote:


It's possible, but I'd rather do the upload in fs. I've been planning an option for OctoPrint, it should be quite straightforward to do the upload. API key and upload folder would be configurable in GUI/CLI.

**Comment by spegelius** [comment]
Octoprint is in release, however testing is quite minimal. closing this for now, open new issue if problems found
