### ISSUE TITLE
Double retraction following prepurge

### ISSUE THREAD

**Issue by paukstelis** [spegelius/filaswitch#49]
I've noticed with the most recent version I get a double retraction at the end of the prepurge:

```
G1 X0 Y0.480 F3000; Y shift
G1 X49.000 Y0 E1.8000 F2200; purge trail
G1 X0 Y0.480 F3000; Y shift
G1 X-49.000 Y0 E1.8000 F2200; purge trail
G1 X0 Y0.480 F3000; Y shift
G1 Z0.7000 F720; z-hop
G90; absolute positioning
M83; relative E
G92 E0; reset extruder
G1 E-4.2000 F3000; retract
;PRIME END
; START SCRIPT END
G1 E-4.2000 F3000
G1 Z0.642 F720
; process Grey
```

I do have Tool Change retract set to 0.

**Comment by spegelius** [comment]
Hmm, wonder why that doesn't happen on my profile... ok I'll probably revert the commit that adds retract after preprime. Detecting if retract is needed would need more work so probably won't waste time with that
