### ISSUE TITLE
Support other than 0.2mm layers?

### ISSUE THREAD

**Issue by spegelius** [spegelius/filaswitch#5]
Higher layers are possible, lower than 0.2 mm might cause problems with the pre-switch purge (too much material to deposit on 0.1mm layer). Wider paths maybe, but probably will cause unwanted blobbing

**Comment by gavatron3000** [comment]
So the pre purge must be completed at a particular rate? I mean the 0.1 would be excellent but can't have the cake and eat it too. I'd be happy to "risk" it but  if it could be done over larger area and purge the right amount of material do you think it would be achievable or is that the limiting factor?

**Comment by spegelius** [comment]
It's not the rate, at least it isn't the limiting factor. It's the amount of material to purge. With 0.1mm layers it means double area for the purge tower and it's doable, I'll just have to calculate the tower size differently. Also the initial fast purge might be bit problematic because it needs to be done at fixed speed/rate, need to figure something out...

**Comment by gavatron3000** [comment]
thought the fixed speed/rate to be the limiting part. maybe widing the tower and including a one extrusion gap between each printed line and offsetting each following layer by one line as to "simulate" a 0.2mm layer but still incrementing 0.1mm .. just brainstorming out loud

**Comment by spegelius** [comment]
Fixed in 0.18.0
