### ISSUE TITLE
Force tower position

### ISSUE THREAD

**Issue by paukstelis** [spegelius/filaswitch#53]
I have run into a few situations where I couldn't fit the wipe tower onto the build plate due to model size, even though there was plenty of build plate available. As a quick-fix, I added a command line argument that  bypasses the position checks and force the tower to start at a particular coordinate. Not sure if this is still being maintained but I could clean it up for a PR if there is interest.
![screenshot from 2018-08-28 21-40-50](https://user-images.githubusercontent.com/28326982/44760154-90f89400-ab0b-11e8-8303-bc0b64c6258e.png)

**Comment by spegelius** [comment]
I've been thinking about implementing something like this so go ahead.
I do have plans for improving filaswitch, not sure when I have time though...
