### ISSUE TITLE
THC-01

### ISSUE THREAD

**Issue by trev502000** [spegelius/filaswitch#64]
Hi i have this error when trying to use the THC-01 setting any ideas? works with all the other hw config 
----------------------

Detected Simplify3D format

HW config: THC-01

ERROR: Gcode processing failed: float() argument must be a string or a number, not 'NoneType'

----------------------

**Comment by spegelius** [comment]
I tried processing file with THC-01 cfg and didn't get any errors. Try the latest 0.21.0 version and if the problem persists, send me the log file from logs-directory

**Comment by trev502000** [comment]
New version works thank you
