### ISSUE TITLE
No Zhop even if enabled..

### ISSUE THREAD

**Issue by TelliMantelli** [spegelius/filaswitch#72]
I cannot get zhop to work between print and tower. I have enable in my config. Do I also enable in S3D?
Thanks!

**Comment by TelliMantelli** [comment]
Here's a link to my config and gcode. https://drive.google.com/open?id=1ucZ8YRqnAdrLgz80fHe8iYcGjfakfqmT

**Comment by spegelius** [comment]
Currently filaswitch follows the slicer settings for z-hop (except for Cura). So if you don't have z-hop enabled in S3D, it won't do it with tower.

**Comment by TelliMantelli** [comment]
Ahhh ok. So as of right now there no way to have zhop between model and tower only..not between each layers also with S3D?

**Comment by spegelius** [comment]
Yes, but that could be changed so that hwcfg tower z-hop value is used always.

**Comment by TelliMantelli** [comment]
That be great to have it work that way! Be willing to test.
