### ISSUE TITLE
Layer shift from build up on Tower 2 PLaces.

### ISSUE THREAD

**Issue by TelliMantelli** [spegelius/filaswitch#73]
On my pruge tower you can see from added photos that on the purge tower Im getting build ups in 2 spots which cause a layer shift. What can I do to reduce this behavoir? Thanks really appreciate all the help lately!
![93600924_1090888597951382_3266827020977307648_n](https://user-images.githubusercontent.com/27321194/79700739-58707580-826e-11ea-8fd6-fb5d65f7df78.jpg)
![93986192_676509226442368_4553454697209397248_n](https://user-images.githubusercontent.com/27321194/79700740-5ad2cf80-826e-11ea-9fbb-312139aa53cc.jpg)

**Comment by spegelius** [comment]
Yuo probably have the new filament feed too long so it builds up too much material. So in hwcfg. make sure the total rapid.retract length is more that the total feed length. Looking at the values you posted, you are feeding quite a lot more that you are retracting, almost 3 times which will cause filament buildup

**Comment by TelliMantelli** [comment]
Ok awesome let me make those changes! Thanks man again really appreciate the help. If I get this worked out my A10m hwcfg should work with all the M series as the only difference is bed size.
