### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by momo9700** [spegelius/filaswitch#75]
I'm currently using the last version of S3D on MacOS and it says this error.

**Comment by spegelius** [comment]
S3D version 5? I don't have that. Can you send me the gcode file for debugging?

**Comment by momo9700** [comment]
the version of S3D is the 4.1.2.
It gives me this error whit any gcode i prepare whit dual extrusion wizard in the slicer

**Comment by spegelius** [comment]
Sorry about the late reply, but I need a gcode file that fails so I can replicate the error. Also if you are using a custom hwcfg file, please send that also

**Comment by momo9700** [comment]
no worries. here is the files.
[files.zip](https://github.com/spegelius/filaswitch/files/6220764/files.zip)

**Comment by spegelius** [comment]
Ok it seems the line 'prepruge.temperature.change: -10' has a typo (prepruge). I'll update filaswitch with better error information.

**Comment by momo9700** [comment]
thanks very much
